add payment validation and view model
apmath-web/credit-go pull request #10
Opened 2018-11-26 12:13 UTC by sashachernyshova

Надо сделать:

- [ ] Описать модель платежа

- [ ] Написать валидацию платежа

2018-11-26 12:27 UTC, malinink commented
Issue где?

2018-11-26 12:36 UTC, sashachernyshova commented
добавлено

2018-11-29 18:17 UTC, malinink requested changes

2018-11-29 18:17 UTC, malinink commented on viewModels/Payment.go
> +	if val, ok := p.JsonData[name]; ok && val != nil && reflect.TypeOf(val).String() == type_ {
мне кажется что я уже похожий check видел в кредите, предлагаю в базовый класс вынести

2018-11-29 18:17 UTC, malinink commented on viewModels/Payment.go
> +	} else {
также мне не очень вот эта конструкция нравится, кажется можно сделать менее вложенно и более понятно.

2018-11-29 18:17 UTC, malinink commented on viewModels/Payment.go
> +	return nil
поставьте // TODO во все методы, которы не реализованы до конца

2018-11-29 18:17 UTC, malinink commented on viewModels/Payment.go
> +		if p.GetState() == "" {
возможно я пропустил, но не слишком ли много оверхеда, т.е. мы при валидации конвертим, а потом для получения еще раз конвертнем, коенчно рабочая тема, но есть повод задуматься о том как бы избежать повторных однообразных действий

2018-12-02 10:43 UTC, malinink commented
@sashachernyshova @levozavr отрефакторил классы, переиспользуйте методы.

2018-12-08 09:46 UTC, malinink approved these changes

2018-12-08 09:48 UTC, merged