Feature 1
apmath-web/credit-go pull request #2
Opened 2018-11-07 16:18 UTC by levozavr

Добавлены следующие интерфейсы
- [ ] ViewModelInterface 
- [ ] CreditInterface
- [ ] PersonInterface
- [ ] PaymentInterface
- [ ] PersonInterface
- [ ] PaymentInterface
- [ ] ValidationInterface
- [ ] MessageInterface
- [ ] CreditInterface
- [ ] CreditsRepositoryInterface

2018-11-08 18:24 UTC, malinink requested changes

2018-11-08 18:24 UTC, malinink commented on models/CreditInterface.go
> +	getPayments(type_ data.Type, state data.State) []valueObjects.PaymentInterface
`type` зарезервировано?

2018-11-08 18:24 UTC, malinink commented on valueObjects/PersonInterface.go
> +/*
Да, в го интерфейсы, как и try-catch вообще рудименты. Предлагаю всёже из интерфейса убрать, а добавить ссылку на что-то вроде https://gobyexample.com/interfaces в wiki проекта, или README.md

2018-11-08 18:24 UTC, malinink commented on valueObjects/ValidationInterface.go
> +	getMessages() []MessageInterface
addMessage() ?

2018-11-08 18:24 UTC, malinink commented on viewModels/ViewModelInterface.go
> +	Fill(JsonData interface{}) (bool, error)
а чего с большой буквы? или методы класса с маленькой тоже будут приватными вне пакета?

2018-11-08 18:24 UTC, malinink commented on models/CreditInterface.go
> +	getAmount() int64
тут я тоже переделал на Money

2018-11-08 18:24 UTC, malinink commented on data/Money.go
> +type Money int64
есть проблема, это всёже не инт ;)
не искали, в го есть что-нибудь готовое, но из коробки.

2018-11-08 19:53 UTC, levozavr commented on models/CreditInterface.go
> +	getPayments(type_ data.Type, state data.State) []valueObjects.PaymentInterface
Увы да(

2018-11-08 19:54 UTC, levozavr commented on data/Money.go
> +type Money int64
чего-то готового увы нет(

2018-11-08 19:55 UTC, levozavr commented on viewModels/ViewModelInterface.go
> +	Fill(JsonData interface{}) (bool, error)
упс, забыл поправить

2018-11-08 19:59 UTC, levozavr commented on valueObjects/ValidationInterface.go
> +	getMessages() []MessageInterface
опечатка, исправлю

2018-11-08 20:10 UTC, levozavr commented
@malinink исправил недочеты, проверьте пожалуйста

2018-11-08 20:22 UTC, levozavr commented on data/Money.go
> +type Money int64
Либо же надо это отдельно обсуждать, так как там в решениях есть некоторый overhead
https://godoc.org/google.golang.org/genproto/googleapis/type/money
https://godoc.org/golang.org/x/text/currency

2018-11-09 07:48 UTC, malinink approved these changes

2018-11-09 07:48 UTC, malinink commented on data/Money.go
> +type Money int64
Пусть пока будет так, как найдем замену - тут заиспользуем.

2018-11-09 07:48 UTC, merged