Создать апи для метода получения списка платежей
apmath-web/credit-go pull request #22
Opened 2018-12-12 07:56 UTC by levozavr

сделано:

- [ ] прописать роутинг
- [ ] получить параметры из ссылки
- [ ] написать обработку ошибок
- [ ] реализовать логику action
- [ ] создать mock ответа bl

2018-12-12 20:03 UTC, malinink requested changes

2018-12-12 20:03 UTC, malinink commented on actions/actions.go
> +	if validPayments.Match(path) && request.Method == "GET" {
Как насчет того, чтобы вначале проверять метод, а потом регулярку? т.к. у нас методов пересекающихся по типу запросу всего 2, это ускорит процесс выбора роута.

2018-12-12 20:03 UTC, malinink commented on actions/payment-get.go
> +	fmt.Fprint(response, "{\"payments\":[{\"type\":\"regular\",\"state\":\"paid\",\"date\":\"2018-10-08\","+
Так а почему тут не используется `jsonBytes`

2018-12-12 21:31 UTC, levozavr commented on actions/payment-get.go
> +	fmt.Fprint(response, "{\"payments\":[{\"type\":\"regular\",\"state\":\"paid\",\"date\":\"2018-10-08\","+
Потому что на данный момент ddd не реализовано и jsonBytes будет пустым

2018-12-12 21:33 UTC, levozavr commented on actions/payment-get.go
> +	fmt.Fprint(response, "{\"payments\":[{\"type\":\"regular\",\"state\":\"paid\",\"date\":\"2018-10-08\","+
Для этого сейчас реализован mock выдающий верный по формату результат

2018-12-13 06:13 UTC, malinink approved these changes

2018-12-13 06:14 UTC, merged