создание viewModel для credit
apmath-web/credit-go pull request #4
Opened 2018-11-10 14:21 UTC by levozavr

сделано:

- [x] создание valueObject Message
- [x] создание valueObject Validation
- [x] создание viewModel Person
- [x] создание viewModel Credit
- [x] описание логики валидации кредита
close #3

2018-11-10 14:41 UTC, levozavr commented
@malinink у меня появились некоторые вопросы:

-  Что должна делать функция Fetch?
-  Что должна делать функция Hydrate?

Так же мне интересно узнать на счет того, что уже сделанно в рамках issue #3

2018-11-10 20:00 UTC, levozavr commented
@malinink  починил ту ошибку исправив дату шаблона на 2006-01-02.

Очень интересная ошибка.

из документации: `time.Parse(layout string, someStr string)`

работает : `date, _ := time.Parse("2006-01-02", "2018-10-10")`  :+1: 
не работает : `date, _ := time.Parse("2006-01-02", "2018-10-10")`  :-1:

2018-11-10 20:42 UTC, levozavr commented
На мой взгляд это готово к проверке @malinink

2018-11-10 22:15 UTC, levkovalenko commented
Так же не думаю что без имплементированного кода стоит пистать функции hydrate и  fetch из-за особенностей GO в плане ссылок, так как это достаточно сложно дебажится и не хочется потом искать багу при интеграции api и ddd

2018-11-11 19:11 UTC, malinink commented
@levozavr 
https://golang.org/pkg/time/#Parse
С датой все верно сделали, это видимо особенность GO указывать формат в таком стиле, кстати что это за дата то такая вы поняли? 
PR погляжу только завтра, по поводу ссылок, передавайте по указателю, там нет проблем, если нужен указатель а у вас объект всегда можно передать &var

Ну а если хочется сделать совсем хорошо - напишите юнит тест.

2018-11-11 23:03 UTC, levozavr commented
@malinink у меня была проблема приведением ссылочных объектов к json формату из-за особенностей языка и стандартных функций.

2018-11-12 07:42 UTC, malinink requested changes

2018-11-12 07:42 UTC, malinink commented on valueObjects/Validation.go
> +func (v *Validation) AddMessages(messages []MessageInterface) {
AddMessage же, нет? т.е. добавляем по 1 сообщению за 1 раз

2018-11-12 07:42 UTC, malinink commented on actions/credit-create.go
> +		fmt.Fprintf(response, "messages:[{\"Package\":\"Invalid json format\"}]")
Есть идея, что если метод будет возвращать ValidationInterface или nil?
Тогда в базовый метод, можно будет перенести PtrMessagesToJson и генерировать все 400 ошибки там.
Пока что это на уровне идеи, что скажете?

2018-11-12 08:59 UTC, levozavr commented on valueObjects/Validation.go
> +func (v *Validation) AddMessages(messages []MessageInterface) {
Тогда возникнет проблема с тем что бы сохранять сообщения о некорректных полях в person
![image](https://user-images.githubusercontent.com/30433199/48336814-469aa400-e672-11e8-9a39-3eb7f5005722.png)
Validation возвращает же массив со сообщениями, а не одно

2018-11-12 09:01 UTC, levozavr commented on actions/credit-create.go
> +		fmt.Fprintf(response, "messages:[{\"Package\":\"Invalid json format\"}]")
давайте поменяем на ValidationInterface, так что бы не было таких захардкоженных пакетов и все имело один стиль

2018-11-12 09:06 UTC, levozavr commented on valueObjects/Validation.go
> +func (v *Validation) AddMessages(messages []MessageInterface) {
иначе придется проходить по всем message из Person.GetValidation().GetMessages() и добавлять их по одному

2018-11-12 09:46 UTC, malinink commented on valueObjects/Validation.go
> +func (v *Validation) AddMessages(messages []MessageInterface) {
По ним неизбежно прийдется проходится, т.к. я бы предложил модифицировать поле `lastName` в что-то вроде `person.lastName` или `person/lastName` т.е. чтобы пониамть где именно ошибка, т.к. lastName теоретически может быть в разных вложенных объектах.

2018-11-12 09:47 UTC, malinink commented on actions/credit-create.go
> +		fmt.Fprintf(response, "messages:[{\"Package\":\"Invalid json format\"}]")
Если есть желание, то можно оставить возможность добавить список ошибок, наряду с возможностью добавить одну ошибку в валидацию.

2018-11-12 11:01 UTC, levozavr commented on valueObjects/Validation.go
> +func (v *Validation) AddMessages(messages []MessageInterface) {
Почему по ним придется ходить?
Мы же можем поле модифицировать во время валидации Person. 
К тому же, почему не может быть возможности добавления нескольких сообщений сразу?

2018-11-12 11:03 UTC, levozavr commented on actions/credit-create.go
> +		fmt.Fprintf(response, "messages:[{\"Package\":\"Invalid json format\"}]")
Не совсем понял о чем вы?

2018-11-12 11:14 UTC, levozavr commented on actions/credit-create.go
> +		fmt.Fprintf(response, "messages:[{\"Package\":\"Invalid json format\"}]")
А и зачем переносить PtrMessagesToJspn в базовый метод? Нам она может много где понядобится, зачем в дальнейшем повторять себя?

2018-11-12 11:17 UTC, levozavr commented on valueObjects/Validation.go
> +func (v *Validation) AddMessages(messages []MessageInterface) {
просто как такого отдельного Person нам не будут присылать, это всегда часть кредита, поэтому почему мы не можем все сообщения полученные при его валидации положить сразу в в сообщения валидации кредита?

2018-11-12 12:49 UTC, levozavr commented
@malinink может стоит обсудить полный формат вывод ошибки и вынести его в спецификацию?
потому что в коде одно, в спецификации другое, а тестах третье, а на деле надо четвертое.

2018-11-12 21:50 UTC, levozavr commented
@malinink внес изменения согласно спецификации и беседы в slack

2018-11-18 19:28 UTC, malinink requested changes
Признаюсь, тесты пока не глядел, попробую завтра с работы глянуть.

2018-11-18 19:28 UTC, malinink commented on actions/credit-create.go
> +func ToJson(response http.ResponseWriter, request *http.Request) (map[string]interface{}, bool) {
точно нужен 2 параметр, мы же путем проверки первого на nil можем сделать все необходимые выводы, нет?

2018-11-18 19:28 UTC, malinink commented on actions/credit-create.go
> +func ToJson(response http.ResponseWriter, request *http.Request) (map[string]interface{}, bool) {
предлагаю общие для всех экшенов методы вынести в `actions.go`
т.е. ToJson и PtrMessagesToJsonErrMessage
также их можно сделать приватными, т.к. их мы будем использовать только из экшенов (ну вроде как)

2018-11-18 19:28 UTC, malinink commented on valueObjects/Message.go
> +func (m *Message) Message(field string, text string) {
Может быть стоит объединить "псевдоконструктор" с GenMessage, т.к. мы реально метод Message нигде использовать не будем, ну и тогда убрать его из интерфейса, и все аналогичные методы, что скажете?

2018-11-18 19:28 UTC, malinink commented on viewModels/Credit.go
> +	if ok, val := c.check("float64", "amount"); ok {
я так понимаю что тут  `if ok` лишнее?

2018-11-18 19:28 UTC, malinink commented on viewModels/Credit.go
> +	if !c.Person.Validate() {
почему нет проверки на наличие персоны? как-то странновато

2018-11-18 19:28 UTC, malinink commented on viewModels/Credit.go
> +	if ok, val := c.check("float64", "percent"); ok {
в общем механика понятна, но как-то странно выглядит портянка из ok val и val ok, может быть с этим что-то можно сделать? например вынести в отдельные функции, как минимум выглядит очень странно

2018-11-18 19:57 UTC, levozavr commented on viewModels/Credit.go
> +	if !c.Person.Validate() {
Проверка есть, она происходит в функции check

2018-11-18 19:58 UTC, levozavr commented on valueObjects/Message.go
> +func (m *Message) Message(field string, text string) {
можно сделать отдельные конструкторы, которые не будут методами класса

2018-11-18 20:01 UTC, levozavr commented on actions/credit-create.go
> +func ToJson(response http.ResponseWriter, request *http.Request) (map[string]interface{}, bool) {
Хм, можно и так

2018-11-18 20:02 UTC, levozavr commented on actions/credit-create.go
> +func ToJson(response http.ResponseWriter, request *http.Request) (map[string]interface{}, bool) {
Да так и сделаю

2018-11-18 20:03 UTC, levozavr commented on viewModels/Credit.go
> +	if ok, val := c.check("float64", "amount"); ok {
Нет, не лишнее

2018-11-18 20:24 UTC, levkovalenko commented on viewModels/Credit.go
> +	if !c.Person.Validate() {
в 56 строке

2018-11-21 07:02 UTC, malinink approved these changes
Можете объяснить почему? Неявно вызывается конструктор?

2018-11-21 07:02 UTC, malinink commented on viewModels/Credit.go
> +	Person        Person `json:"person"`
С интерфейсом этот код не работает?

2018-11-21 09:05 UTC, levozavr commented on viewModels/Credit.go
> +	Person        Person `json:"person"`
Потому что там у нас нужен не интерфейс к типу данных, а сам тип так как мы его заполняем и работаем с ним

2018-11-21 09:05 UTC, levozavr commented on viewModels/Credit.go
> +	Person        Person `json:"person"`
Потому что нам здесь нужен сам типа данных, а не интерфейс к нему.

2018-11-21 09:40 UTC, malinink commented on viewModels/Credit.go
> +	Person        Person `json:"person"`
Довольно странно, но ладно.

2018-11-21 09:40 UTC, merged